"""initial

Revision ID: 29d88b269d4f
Revises: 
Create Date: 2022-03-23 23:05:33.718903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d88b269d4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number1', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('number2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('result', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Index('id_operator', 'operator'),
    sa.Index('id_result', 'result'),
    sa.PrimaryKeyConstraint('id', name='new_table_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_operator', 'math_expression')
    op.drop_index('id_result', 'math_expression')
    op.drop_table('new_table')
    # ### end Alembic commands ###
