"""empty message

Revision ID: 4re6q2xsb7nm
Revises:
Create Date: 2022-03-23 03:02:40.908172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4re6q2xsb7nm'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_table2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number1', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('number2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('result', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Index('id_oper_num1_num2', 'operator', 'number1', 'number2'),
    sa.PrimaryKeyConstraint('id', name='new_table_pkey'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_table2')
    # ### end Alembic commands ###
