"""add new ind

Revision ID: c1c4f004f50c
Revises: 29d88b269d4f
Create Date: 2022-03-23 23:24:46.901560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c4f004f50c'
down_revision = '29d88b269d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_result_and_operator', 'new_table', ['result', 'operator'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_result_and_operator', table_name='new_table')
    # ### end Alembic commands ###
